databases:
  - user: asdf
    password: asdf
    host: 123.123.123.123
    port: 1234
  - user: asdf
    password: asdf
    host: 123.123.123.123
    port: 1234

tests:
  - filename: ./assets/sql/test1.xml
    cases:
      - id: case1
        params:
          id: asdf

      - id: case1
        params:
          id: a

      - id: case1
        params:
          id: b

  - filename: asdf
    cases:
      - id: asdf

  - filename: asdf
    cases:
      - id: asdf
