databaseConnections:
  - user: postgres
    password: naverscv!23
    host: 127.0.0.1
    port: 5432
    database: postgres

  - user: postgres
    password: naverscv!23
    host: 127.0.0.1
    port: 5432
    database: postgres

tests:
  - filename: ./assets/sql/test1.xml
    cases:
      - id: case1
        params:
          id: asdf

      - id: case1
        params:
          id: a

      - id: case1
        params:
          id: b

  - filename: asdf
    cases:
      - id: asdf

  - filename: asdf
    cases:
      - id: asdf
